{% set name = "py2exe" %}
{% set version = "0.11.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/py2exe/py2exe/archive/v{{ version }}.tar.gz
  sha256: 6cd7bd3f1f763eaecf28d2341b6a71e63927dc91c4611e500e4a43b2ecda32ea

build:
  number: 2
  entry_points:
    - build_exe = py2exe.build_exe:main
  skip: true  # [ not win]
  skip: true  # [ py < 36]

  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - setuptools
  host:
    - setuptools
    - pip
    - python
    # package imports itself at build time
    - pefile
    - cachetools
  run:
    - cachetools
    - pefile
    - python
    - setuptools

test:
  imports:
    - py2exe
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://www.py2exe.org/
  dev_url: https://github.com/py2exe/py2exe
  doc_url: http://www.py2exe.org/index.cgi/Tutorial
  summary: Build standalone executables for Windows
  license: MIT AND X11 AND MPL-2.0
  license_file:
    - LICENSE.txt
    - MPL2-License.txt
    - MIT-License.txt
  description: |
    `py2exe` is a distutils extension which allows to build standalone Windows executable programs (32-bit and 64-bit) from Python scripts

extra:
  recipe-maintainers:
    - HeavyTony2
