{% set name = "py2exe" %}
{% set version = "0.13.0.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/py2exe/py2exe/archive/v{{ version }}.tar.gz
  sha256: ef2907f5b82ec8b2259bea41a2d7d798ecd67aa4a92a74a06550b9123dadd8a4

build:
  number: 2
  skip: true  # [ not win]
  skip: true  # [ py >= 312]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - setuptools
    - pip
    - python
    # package imports itself at build time
    - pefile
    - cachetools
  run:
    - cachetools
    - pefile
    - python

test:
  imports:
    - py2exe
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://www.py2exe.org/
  dev_url: https://github.com/py2exe/py2exe
  doc_url: http://www.py2exe.org/index.cgi/Tutorial
  summary: Build standalone executables for Windows
  license: MIT AND X11 AND MPL-2.0
  license_file:
    - LICENSE.txt
    - MPL2-License.txt
    - MIT-License.txt
  description: |
    `py2exe` is a distutils extension which allows to build standalone Windows executable programs (32-bit and 64-bit) from Python scripts

extra:
  recipe-maintainers:
    - HeavyTony2
