schema_version: 1

context:
  version: "0.14.2.0"

package:
  name: py2exe
  version: ${{ version }}

source:
  url: https://github.com/py2exe/py2exe/archive/v${{ version }}.tar.gz
  sha256: 78d98d395a9192e5da12931613f858b201e056e345e93ec3899b85b92e89e9e4

build:
  number: 0
  skip: not win or match(python, ">=3.15")
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
  host:
    - setuptools
    - pip
    - python
    # package imports itself at build time
    - pefile
    - cachetools
    - wheel
  run:
    - cachetools
    - pefile
    - python
    - setuptools
    - packaging

tests:
  - python:
      imports:
        - py2exe
      pip_check: true

about:
  summary: Build standalone executables for Windows
  license: MIT AND X11 AND MPL-2.0
  license_file:
    - LICENSE.txt
    - MPL2-License.txt
    - MIT-License.txt
  description: |
    `py2exe` is a distutils extension which allows to build standalone Windows executable programs (32-bit and 64-bit) from Python scripts
  homepage: http://www.py2exe.org/
  repository: https://github.com/py2exe/py2exe
  documentation: http://www.py2exe.org/index.cgi/Tutorial

extra:
  recipe-maintainers:
    - HeavyTony2
